To create the files need for uploading an assembly, all you need is pandas and bioframe (https://bioframe.readthedocs.io/)

In [ ]:
import pandas as pd
import bioframe

If you have an assembly where you can fetch centromeres from the UCSC database via bioframe:

In [28]:
centromeres = bioframe.fetch_centromeres("hg38")
centromeres

    chrom      start        end        mid
0    chr1  122026459  124932724  123479591
1   chr10   39686682   41593521   40640101
2   chr11   51078348   54425074   52751711
3   chr12   34769407   37185252   35977329
4   chr13   16000000   18051248   17025624
5   chr14   16000000   18173523   17086761
6   chr15   17083673   19725254   18404463
7   chr16   36311158   38265669   37288413
8   chr17   22813679   26616164   24714921
9   chr18   15460899   20861206   18161052
10  chr19   24498980   27190874   25844927
11   chr2   92188145   94090557   93139351
12  chr20   26436232   30038348   28237290
13  chr21   10864560   12915808   11890184
14  chr22   12954788   15054318   14004553
15   chr3   90772458   93655574   92214016
16   chr4   49712061   51743951   50728006
17   chr5   46485900   50059807   48272853
18   chr6   58553888   59829934   59191911
19   chr7   58169653   61528020   59848836
20   chr8   44033744   45877265   44955504
21   chr9   43389635   45518558   44454096
22   chrX   58605579   62412542   60509060
23   chrY   10316944   10544039   10430491

Fetch the sizes:(per default bioframes fetches from the UCSC database)

In [30]:
chromsizes = bioframe.fetch_chromsizes("hg38")
chromsizes_frame = chromsizes.reset_index().query("index != 'chrM'")
chromsizes_frame.to_csv("hg38.chrom.sizes", sep="\t", header=None, index=False)
chromsizes_frame

    index     length
0    chr1  248956422
1    chr2  242193529
2    chr3  198295559
3    chr4  190214555
4    chr5  181538259
5    chr6  170805979
6    chr7  159345973
7    chr8  145138636
8    chr9  138394717
9   chr10  133797422
10  chr11  135086622
11  chr12  133275309
12  chr13  114364328
13  chr14  107043718
14  chr15  101991189
15  chr16   90338345
16  chr17   83257441
17  chr18   80373285
18  chr19   58617616
19  chr20   64444167
20  chr21   46709983
21  chr22   50818468
22   chrX  156040895
23   chrY   57227415

Now we create the arms out of chromsizes and centromeres.

In [35]:
arms = bioframe.make_chromarms(chromsizes, centromeres)
arms[['chrom','start','end']].to_csv('arms.hg38',index=False)
arms[['chrom','start','end']]

    chrom      start        end
0    chr1          0  123479591
1    chr1  123479591  248956422
2    chr2          0   93139351
3    chr2   93139351  242193529
4    chr3          0   92214016
5    chr3   92214016  198295559
6    chr4          0   50728006
7    chr4   50728006  190214555
8    chr5          0   48272853
9    chr5   48272853  181538259
10   chr6          0   59191911
11   chr6   59191911  170805979
12   chr7          0   59848836
13   chr7   59848836  159345973
14   chr8          0   44955504
15   chr8   44955504  145138636
16   chr9          0   44454096
17   chr9   44454096  138394717
18  chr10          0   40640101
19  chr10   40640101  133797422
20  chr11          0   52751711
21  chr11   52751711  135086622
22  chr12          0   35977329
23  chr12   35977329  133275309
24  chr13          0   17025624
25  chr13   17025624  114364328
26  chr14          0   17086761
27  chr14   17086761  107043718
28  chr15          0   18404463
29  chr15   18404463  101991189
30  chr16          0   37288413
31  chr16   37288413   90338345
32  chr17          0   24714921
33  chr17   24714921   83257441
34  chr18          0   18161052
35  chr18   18161052   80373285
36  chr19          0   25844927
37  chr19   25844927   58617616
38  chr20          0   28237290
39  chr20   28237290   64444167
40  chr21          0   11890184
41  chr21   11890184   46709983
42  chr22          0   14004553
43  chr22   14004553   50818468
44   chrX          0   60509060
45   chrX   60509060  156040895
46   chrY          0   10430491
47   chrY   10430491   57227415
48   chrM          0      16569

If centromeres can not be fetched for our genome:

In [37]:
centromeres = bioframe.fetch_centromeres("mm9")
centromeres

Empty DataFrame
Columns: [chrom, start, end, mid]
Index: []

We can simply take the midpoint as centromeres, since we only use the arms for optimization purposes.

_Future version of HiCognition might only need the chromsizes._

In [1]:
chromsizes = bioframe.fetch_chromsizes("mm9")
chromsizes_frame = chromsizes.reset_index().query("index != 'chrM'")

chromsizes_frame.to_csv("mm9.chrom.sizes", sep="\t", header=None, index=False)

# take center as centromeres
centromeres = chromsizes//2


arms = [
    arm
    for chrom in chromsizes_frame["index"]
    for arm in (
        (chrom, 0, centromeres.get(chrom, 0)),
        (chrom, centromeres.get(chrom, 0), chromsizes.get(chrom, 0)),
    )
]

# construct dataframe out of arms
arms = pd.DataFrame(arms, columns=["chrom", "start", "end"])

arms.to_csv("arms.mm9", index=False)